### PR TITLE
Add Max Connections Per IP

### PR DESCRIPTION
**Pull request by AkmalFairuz**

### CODE REVIEW

**Comment by IndianBartonka** [comment]
maybe you could make a plugin that would do that? I'd love to use that

**Comment by AkmalFairuz** [comment]
> maybe you could make a plugin that would do that? I'd love to use that

This should be added to WaterdogPE, to fix this security vulnerability: https://github.com/pmmp/PocketMine-MP/security/advisories/GHSA-474q-9hgp-hcvx

**Comment by Alemiz112** [comment]
> This should be added to WaterdogPE, to fix this security vulnerability: [GHSA-474q-9hgp-hcvx](https://github.com/pmmp/PocketMine-MP/security/advisories/GHSA-474q-9hgp-hcvx)

To clarify, we do not include pending sessions in player count, so this does not affect WDPE, no events will be called until user sends a LoginPacket.
However, connection throttling will be added part of #253 changes.

**Comment by AkmalFairuz** [comment]
> > This should be added to WaterdogPE, to fix this security vulnerability: [GHSA-474q-9hgp-hcvx](https://github.com/pmmp/PocketMine-MP/security/advisories/GHSA-474q-9hgp-hcvx)
> 
> To clarify, we do not include pending sessions in player count, so this does not affect WDPE, no events will be called until user sends a LoginPacket. However, connection throttling will be added part of #253 changes.

It affect WDPE, my server got attacked with that method. 
https://github.com/CloudburstMC/Network/blob/3d38d50d4360d1dd3f48683eed8a43c5d2e6a139/raknet/src/main/java/com/nukkitx/network/raknet/RakNetServer.java#L42

The attacker sent 1024 connections to proxy without sending LoginPacket

**Comment by AkmalFairuz** [comment]
It counts with unauthenticated connections.
https://github.com/CloudburstMC/Network/blob/3d38d50d4360d1dd3f48683eed8a43c5d2e6a139/raknet/src/main/java/com/nukkitx/network/raknet/RakNetServer.java#L144

https://github.com/CloudburstMC/Network/blob/3d38d50d4360d1dd3f48683eed8a43c5d2e6a139/raknet/src/main/java/com/nukkitx/network/raknet/RakNetServer.java#L197

**Comment by Alemiz112** [comment]
Closing this as a connection throttling was now implemented in WDPE 2.0.0, which was not merged into snapshot (master branch).

**Pull request closed without merging**
