### PR TITLE
Fixed immobile players able to move (#145)

### PR DESCRIPTION
**Pull request by irrld**

### CODE REVIEW

**Comment by TobiasG-DE** [comment]
My issue with this is that if we keep these values synchronized between servers, the immobile state will get out of sync.

**Comment by irrld** [comment]
It will be reset when another server sents SetEntityDataPacket, not exactly synchronizing it between servers. Its just keeping what the server sent after login.

**Comment by TobiasG-DE** [comment]
Well but the other server won't know whether that player is immobile or not won't they?

**Comment by irrld** [comment]
Actually not, because this pr is just about keeping what the current downstream sent.
Isn't PlayStatusPacket.PLAYER_SPAWN sent after SetEntityDataPacket from downstream?

**Comment by irrld** [comment]
This will be probably better, incase downstream changes other things on the EntityMetadata.

**Comment by Alemiz112** [comment]
Implemented this properly in f8563e33054f69d4594602b56ab8e9f574331537

**Pull request closed without merging**
