### PR TITLE
Set level name in InitialHandler

### PR DESCRIPTION
**Pull request by KCodeYT**

### CODE REVIEW

**Comment by TobiasGrether** [comment]
I'm wondering whether its smart to use the MOTD here. Might be better to introduce a separate configuration option for this.

**Comment by KCodeYT** [comment]
> I'm wondering whether its smart to use the MOTD here. Might be better to introduce a separate configuration option for this.

Yea I thought that too, but motd is changeable via `ProxyQueryEvent` so I thought it's good, but I can introduce a new config value if you want to.

**Comment by KCodeYT** [comment]
If you want I can add this value to the ProxyConfig:
```java
@Path("listener.name")
@Comment("The name that is shown up in the player list (pause menu)")
private String name = "§bWaterdog§3PE";
```

**Comment by Alemiz112** [comment]
Whats the point of this? Setting it to MOTD is definitelly not a good idea. I think it is better to leave it on the first server to define LevelName.

**Comment by KCodeYT** [comment]
> Whats the point of this? Setting it to MOTD is definitelly not a good idea. I think it is better to leave it on the first server to define LevelName.

The point is that the proxy should define this text and not the first (in very much every case random) server. Thats why I think this is a good change. If you dont think so you can close this pull request,

**Comment by irrld** [comment]
I also agree to kevims, since it's random in most cases, proxy should decide what's level name is.

**Comment by Alemiz112** [comment]
If this is going to be implemented, than I would suggest not to use just a raw value from the config. Some people may want to change it during runtime, however adding another event isn't good idea as well. 
There can be added new field into `RewriteData`, which can initially hold some config value, and can be overridden by a plugin from login events.

**Comment by KCodeYT** [comment]
> If this is going to be implemented, than I would suggest not to use just a raw value from the config. Some people may want to change it during runtime, however adding another event isn't good idea as well. There can be added new field into `RewriteData`, which can initially hold some config value, and can be overridden by a plugin from login events.

Done!

**Review by Alemiz112 — APPROVED** [review]
Thanks, approved!

**Pull request merged**
