### PR TITLE
Downstream, ServerInfo types

### PR DESCRIPTION
**Pull request by Alemiz112**
This PR implements support of custom ServerInfo classes that allows developer to extend default downstream behaviour. This also comes with new api for custom downstream connections such as TCP...

### CODE REVIEW

**Comment by Alemiz112** [comment]
Getting all things almost ready for merge. Most of the api changes have been already made. Needs proper testing and we should be fine to merge.

**Review by TobiasG-DE — CHANGES_REQUESTED** [review]
All good, but as anchor-points for the API, DownstreamClient and DownstreamSession should have proper documented methods

**Comment by Alemiz112** [comment]
> All good, but as anchor-points for the API, DownstreamClient and DownstreamSession should have proper documented methods

True 😊

**Review by TobiasG-DE — APPROVED** [review]
Looks good, docs will be helpful in the future!

**Pull request merged**
