### PR TITLE
Update Java 8 branch

### PR DESCRIPTION
**Pull request by KCodeYT**
This pull request includes:
- Merge `master` branch to `java-8`
- Fix one bug in java 11 to java 8 conversation

### CODE REVIEW

**Comment by TobiasG-DE** [comment]
Does Java 8 really need the specifically typed diamond operator types? I believe java 8 is able to detect that just as java 11 Is but correct me if I'm wrong

**Comment by KCodeYT** [comment]
> Does Java 8 really need the specifically typed diamond operator types? I believe java 8 is able to detect that just as java 11 Is but correct me if I'm wrong

Yes Java 8 need them if you want to use inner class methods

**Comment by Alemiz112** [comment]
It seems like Jenkinsfile was malformed during the merge. https://jenkins.waterdog.dev/job/Waterdog/job/WaterdogPE/job/PR-41/3/console

**Comment by KCodeYT** [comment]
> It seems like Jenkinsfile was malformed during the merge. https://jenkins.waterdog.dev/job/Waterdog/job/WaterdogPE/job/PR-41/3/console

Its the same jenkins file only the jdk got modified

**Pull request closed without merging**
