### PR TITLE
Implement dimension change screen

### PR DESCRIPTION
**Pull request by Alemiz112**
I have already tested it, but before merging we should test it even more with different devices.

### CODE REVIEW

**Comment by Alemiz112** [comment]
[Dimension change implementation](https://trello.com/c/YF413S9y/50-dimension-change-implementation)

**Review by TobiasG-DE — APPROVED** [review]
Looks good and works on production, no reason for me not to merge it

**Comment by Alemiz112** [comment]
@TobiasG-DE please recheck it once again. If all is right, I will finally merge it this week.

**Review by TobiasG-DE — APPROVED** [review]
Looks good to me, works reasonably well on production @ NG as well

**Pull request merged**
